name: "Sync Data"

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.DATALK_GITHUB_TOKEN}}
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm ci
      - run: make build
      - run: |
          git config user.name datalk
          git config user.email k.tichy@arr-nisa.cz
          git add .
          git commit -m "Data: sync $(date +'%Y-%m-%dT%H:%M:%S')" || true
          git push
